WebApplication7/Models/Appointment.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication7.Models
{
    public class Appointment
    {
        [Key]
        public int appointmentID { get; set; }

        [ForeignKey("user")]
        public string? userID { get; set; }

        [ForeignKey("doctor")]
        public int doctorID { get; set; }

        public AppUser? user { get; set; }

        public Doctor? doctor { get; set; }

        //public int clinicId { get; set; }

        public DateTime appointmentDate { get; set; }

        public bool? isBooked {  get; set; }
    }
}

WebApplication7/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication7.Data;
using WebApplication7.Models;
using WebApplication7.Models.DTO;

namespace WebApplication7.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<AppUser> _userManager;

        public AppointmentsController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            appointmentExpiredControl();
            var applicationDbContext = _context.Appointments.Include(a => a.doctor).Include(a => a.user);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: MyAppointments
        public async Task<IActionResult> MyAppointments()
        {
            appointmentExpiredControl();
            string currentUserId = _userManager.GetUserId(User);
            var applicationDbContext = _context.Appointments
                .Where(x => x.userID == currentUserId && x.isBooked == true)
                .Include(a => a.doctor)
                .ThenInclude(b => b.clinic)
                .OrderBy(a => a.appointmentDate);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.doctor)
                .ThenInclude(b => b.clinic)
                .Include(a => a.user)
                .FirstOrDefaultAsync(m => m.appointmentID == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // GET: Appointments/Create
        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            ViewData["Clinics"] = new SelectList(_context.Clinics, "clinicId", "clinicName");
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("appointmentID,userID,doctorID,appointmentDate,isBooked,clinicId")] Appointment appointment)
        {
            appointment.isBooked = false;

            if (ModelState.IsValid)
            {
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Klinik değiştikçe doktor listesini güncelle
            //ViewData["Clinics"] = new SelectList(_context.Clinics, "clinicId", "clinicName", appointment.clinicId);
            //ViewData["Doctors"] = new SelectList(_context.Doctors.Where(d => d.clinicId == appointment.clinicId), "doctorId", "firstName", appointment.doctorID);

            return View(appointment);
        }

        public JsonResult GetDoctorsByClinicId(int clinicId)
        {
            return Json(_context.Doctors
                .Where(x =>x.clinicId==clinicId)
                .ToList());
        }

        // GET: Appointments/Edit/5
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            ViewData["doctorID"] = new SelectList(_context.Doctors, "doctorId", "firstName", appointment.doctorID);
            ViewData["userID"] = new SelectList(_context.Users, "Id", "Id", appointment.userID);
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("appointmentID,userID,doctorID,appointmentDate,isBooked")] Appointment appointment)
        {
            if (id != appointment.appointmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.appointmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["doctorID"] = new SelectList(_context.Doctors, "doctorId", "firstName", appointment.doctorID);
            ViewData["userID"] = new SelectList(_context.Users, "Id", "Id", appointment.userID);
            return View(appointment);
        }
        public JsonResult GetAppointmentsByDoctorId(int doctorId)
        {
            return Json(_context.Appointments.Where(x => x.doctorID == doctorId && x.isBooked == false).ToList());
        }

        public IActionResult Reserve()
        {
            ViewData["Clinics"] = new SelectList(_context.Clinics, "clinicId", "clinicName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Reserve([Bind("doctorId,appointmentDate")] AppointmentDto appointment)
        {
            appointmentExpiredControl();

            if (ModelState.IsValid)
            {
                Appointment userAppointment = _context.Appointments.Where(x => x.doctorID == appointment.doctorId && x.appointmentDate == appointment.appointmentDate).FirstOrDefault();

                if(userAppointment != null) {
                    userAppointment.isBooked = true;
                    userAppointment.userID = _userManager.GetUserId(User);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(MyAppointments));
            }

            // Klinik değiştikçe doktor listesini güncelle
            //ViewData["Clinics"] = new SelectList(_context.Clinics, "clinicId", "clinicName", appointment.clinicId);
            //ViewData["Doctors"] = new SelectList(_context.Doctors.Where(d => d.clinicId == appointment.clinicId), "doctorId", "firstName", appointment.doctorID);

            return RedirectToAction(nameof(MyAppointments));
        }

        // GET: Appointments/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.doctor)
                .Include(a => a.user)
                .FirstOrDefaultAsync(m => m.appointmentID == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Appointments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Appointments'  is null.");
            }
            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment != null)
            {
                _context.Appointments.Remove(appointment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> CancelAppointment(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.doctor)
                .Include(a => a.user)
                .FirstOrDefaultAsync(m => m.appointmentID == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        [HttpPost, ActionName("CancelAppointment")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CancelAppointmentConfirmed(int id)
        {
            if (_context.Appointments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Appointments'  is null.");
            }
            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment != null)
            {
                appointment.isBooked = false;
            }

WebApplication7/Views/Appointments/CancelAppointment.cshtml
@model WebApplication7.Models.Appointment

@{
    ViewData["Title"] = "Delete";
}

<div class="shadow p-3 mb-5 bg-white rounded" id="centeredContent">

    <div class="text-center"><h3>@_localization.Getkey("İptalEmin")</h3> </div>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.doctor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.doctor.firstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.appointmentDate)
        </dt>
        <dd class="col-sm-10">
                <div style="width: 100px; display: inline-block;"></div>@Html.DisplayFor(model => model.appointmentDate)
        </dd>
    </dl>

    <form asp-action="CancelAppointment">
        <input type="hidden" asp-for="appointmentID" />
        <div class="text-center">
        <input type="submit" value="@_localization.Getkey("İptalEt")" class="btn btn-danger" /> |
        <a asp-action="MyAppo   intments" class="btn btn-primary">@_localization.Getkey("GeriDön")</a>
            </div>
    </form>
</div>
</div>

WebApplication7/Views/Appointments/Create.cshtml
@model WebApplication7.Models.Appointment

@{
    ViewData["Title"] = "Create";
}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>


<h1>Create</h1>

<h4>Appointment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Klinik</label>
                <select  id="clinicId" class="form-control" asp-items="ViewBag.Clinics">
                    <option disabled selected>---- Klinik Seçiniz ----</option>
                </select>
            </div class="form-group">
                <label asp-for="doctorID" class="control-label"></label>
                <select asp-for="doctorID" class="form-select" id="doctorId"></select>
             <div class="form-group">
                <label asp-for="appointmentDate" class="control-label"></label>
                <input asp-for="appointmentDate" class="form-control" />
                <span asp-validation-for="appointmentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-create" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-back">Back to List</a>
</div>

@section Scripts {

    <script>
        $(document).ready(function () {
            GetDoctorsByClinicId();

            $("#clinicId").change(function () {
                GetDoctorsByClinicId();
            });
        });

        var GetDoctorsByClinicId = function () {
            $.ajax({
                url: '@Url.Action("GetDoctorsByClinicId", "Appointments")',
                type: 'GET',
                data: {
                    clinicId: $('#clinicId').val()
                },
                success: function (data) {
                    $('#doctorId').empty(); // Önce mevcut seçenekleri temizle
                    $(data).each(function (index, item) {
                        $('#doctorId').append('<option value="' + item.doctorId + '">' + item.firstName + " " + item.lastName + '</option>');
                    });
                }
            });
        };
    </script>

}

WebApplication7/Views/Appointments/Delete.cshtml
@model WebApplication7.Models.Appointment

@{
    ViewData["Title"] = "Delete";
}

<div class="shadow p-3 mb-5 bg-white rounded" id="centeredContent">
<h3>@_localization.Getkey("SilmekEmin")</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.user)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.user.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.doctor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.doctor.firstName)
        </dd>
        <dt class = "col-sm-2">
            Date
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.appointmentDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="appointmentID" />
            <div class="d-flex justify-content-center align-items-center">
            <input type="submit" value=@_localization.Getkey("Delete") class="btn btn-danger" /> |
            <a asp-action="Index" class="btn btn-primary">@_localization.Getkey("GeriDön")</a>
            </div>
    </form>
</div>
</div>

WebApplication7/Views/Appointments/Details.cshtml
@model WebApplication7.Models.Appointment

@{
    ViewData["Title"] = "Details";
}
<div style="width :400px" class="shadow p-3 mb-5 bg-white rounded" id="centeredContent">

    <div class="text-center"><h1>@_localization.Getkey("RandevuBilgileri")</h1></div>
    <div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.doctor.clinic)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.doctor.clinic.clinicName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.doctor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.doctor.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.appointmentDate)
        </dt>
        <dd class = "col-sm-10">
                <div style="width: 100px; display: inline-block;"></div>@Html.DisplayFor(model => model.appointmentDate)

        </dd>
    </dl>
</div>
<div class="text-center">
    @if (User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.appointmentID" class="btn btn-success">Edit</a>
    }    
    
        @{
            if (User.IsInRole("Admin"))
            {
                <a asp-action="Index" class="btn btn-primary">Back to List</a>
            }
            else
            {
                <a asp-action="MyAppointments" class="btn btn-primary">Back to List</a>
            }
        }
    
</div>
</div>

WebApplication7/Views/Appointments/Edit.cshtml
@model WebApplication7.Models.Appointment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Appointment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="appointmentID" />
            <div class="form-group">
                <label asp-for="userID" class="control-label"></label>
                <select asp-for="userID" class="form-control" asp-items="ViewBag.userID"></select>
                <span asp-validation-for="userID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="doctorID" class="control-label"></label>
                <select asp-for="doctorID" class="form-control" asp-items="ViewBag.doctorID"></select>
                <span asp-validation-for="doctorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="appointmentDate" class="control-label"></label>
                <input asp-for="appointmentDate" class="form-control" />
                <span asp-validation-for="appointmentDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isBooked" /> @Html.DisplayNameFor(model => model.isBooked)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication7/Views/Appointments/Index.cshtml
@model IEnumerable<WebApplication7.Models.Appointment>

@{
    ViewData["Title"] = "Index";
}

<h1>@_localization.Getkey("Randevular").Value</h1>

<p>
    <a asp-action="Create" class="btn btn-create">@_localization.Getkey("YeniEkle").Value</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @_localization.Getkey("User").Value
            </th>
            <th>
                @_localization.Getkey("Doktor").Value
            </th>
            <th>
                @_localization.Getkey("Tarih").Value
            </th>
            <th>
                @_localization.Getkey("RezerveMi").Value
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
             <td>@{
                        if(item.userID == null)
                        {
                            <h5>boş</h5>
                        }
                        
                        else{
                            <h5> @Html.DisplayFor(modelItem => item.user.firstName) </h5>
                        }
                }   
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doctor.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.appointmentDate)
            </td>
            <td>

                    @{
                        if(item.isBooked== false)
                        {
                            <h5>rezerve edilmedi</h5>
                        }
                        else
                        {

                            <h5>rezerve</h5>
                        }
                    }
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.appointmentID" class="btn btn-table btn-outline-success">@_localization.Getkey("Edit").Value</a>
                    <a asp-action="Details" asp-route-id="@item.appointmentID" class="btn btn-table btn-outline-info">@_localization.Getkey("Details").Value</a>
                    <a asp-action="Delete" asp-route-id="@item.appointmentID" class="btn btn-table btn-outline-danger">@_localization.Getkey("Delete").Value</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication7/Views/Appointments/MyAppointments.cshtml
@model IEnumerable<WebApplication7.Models.Appointment>

    <h1>@_localization.Getkey("Randevularım")</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.doctor.clinic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.doctor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.appointmentDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @Html.DisplayFor(modelItem => item.doctor.clinic.clinicName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.doctor.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.appointmentDate)
            </td>
            <td>
                    <a asp-action="Details" asp-route-id="@item.appointmentID" class="btn btn-table btn-outline-info">@_localization.Getkey("Details")</a> 
                    <a asp-action="CancelAppointment" asp-route-id="@item.appointmentID" class="btn btn-table btn-outline-danger">@_localization.Getkey("İptalEt")</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication7/Views/Appointments/Reserve.cshtml
@model WebApplication7.Models.DTO.AppointmentDto

@{
    ViewData["Title"] = "Reserve";
}

<h1>@_localization.Getkey("RandevuAl")</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Reserve">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label  class="control-label">@_localization.Getkey("Klinik")</label>
                <select id="clinicId" class="form-control" asp-items="ViewBag.Clinics">
                    <option disabled selected>---- Klinik Seçiniz ----</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="doctorId" class="control-label">@_localization.Getkey("Doktor")</label>
                <select asp-for="doctorId" class="form-select" id="doctorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="appointmentDate" class="control-label">@_localization.Getkey("Tarih")</label>
                <select asp-for="appointmentDate"  class="form-select" id="appointmentDate"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>

        $(document).ready(function () {
            GetDoctorsAndAppointments();

            $("#clinicId").change(function () {
                GetDoctorsAndAppointments();
            });
        });

        var GetDoctorsAndAppointments = function () {
            GetDoctorsByClinicId();

            $("#doctorId").change(function () {
                GetAppointmentsByDoctorId();
            });

            GetAppointmentsByDoctorId();
        };

        var GetDoctorsByClinicId = function () {
            $.ajax({
                url: '@Url.Action("GetDoctorsByClinicId", "Appointments")',
                type: 'GET',
                data: {
                    clinicId: $('#clinicId').val()
                },
                success: function (data) {
                    $('#doctorId').empty();
                    $(data).each(function (index, item) {
                        $('#doctorId').append('<option value="' + item.doctorId + '">' + item.firstName + " " + item.lastName + '</option>');
                    });
                    if (data.length > 0) {
                        $('#doctorId').val(data[0].doctorId);
                    }
                    GetAppointmentsByDoctorId();
                }
            });
        };

        var GetAppointmentsByDoctorId = function () {
            $.ajax({
                url: '@Url.Action("GetAppointmentsByDoctorId", "Appointments")',
                type: 'GET',
                data: {
                    doctorId: $('#doctorId').val()
                },
                success: function (data) {
                    $('#appointmentDate').empty();
                    $(data).each(function (index, item) {
                        $('#appointmentDate').append('<option value="' + item.appointmentDate + '">' + item.appointmentDate + '</option>');
                    });
                },
                error: function (error) {
                    console.error("An error occurred while fetching appointments: ", error);
                    // Burada kullanıcıya bir hata mesajı gösterebilirsiniz.
                }
            });
        };


    </script>
}