WebApplication7/Controllers/ClinicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WebApplication7.Data;
using WebApplication7.Models;

namespace WebApplication7.Controllers
{
    public class ClinicsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly HttpClient _httpClient;

        public ClinicsController(ApplicationDbContext context)
        {
            _context = context;
            _httpClient = new HttpClient();
        }

        // GET: Clinics
        public async Task<IActionResult> Index()
        {
            List<Clinic> klinikler = new List<Clinic>();

            var response = await _httpClient.GetAsync("https://localhost:7196/api/ClinicsApi");
            var jsonResponse = await response.Content.ReadAsStringAsync();
            klinikler = JsonConvert.DeserializeObject<List<Clinic>>(jsonResponse);
            return View(klinikler);
        }

        // GET: Clinics/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            Clinic klinik = new Clinic();

            var response = await _httpClient.GetAsync("https://localhost:7196/api/ClinicsApi/" + id);
            var jsonResponse = await response.Content.ReadAsStringAsync();
            klinik = JsonConvert.DeserializeObject<Clinic>(jsonResponse);

            return View(klinik);
        }

        // GET: Clinics/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clinics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("clinicId,clinicName")] Clinic clinic)
        {
            if (ModelState.IsValid)
            {
                string data = JsonConvert.SerializeObject(clinic);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage responseMessage = await _httpClient.PostAsync("https://localhost:7196/api/ClinicsAPi/", content);

                if (responseMessage.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(clinic);
        }

        // GET: Clinics/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clinics == null)
            {
                return NotFound();
            }

            var clinic = await _context.Clinics.FindAsync(id);
            if (clinic == null)
            {
                return NotFound();
            }
            return View(clinic);
        }

        // POST: Clinics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("clinicId,clinicName")] Clinic clinic)
        {
            if (ModelState.IsValid)
            {
                string data = JsonConvert.SerializeObject(clinic);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage responseMessage = await _httpClient.PutAsync("https://localhost:7196/api/ClinicsAPi/" + id, content);

                if (responseMessage.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(clinic);
        }

        // GET: Clinics/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clinics == null)
            {
                return NotFound();
            }

            var clinic = await _context.Clinics
                .FirstOrDefaultAsync(m => m.clinicId == id);
            if (clinic == null)
            {
                return NotFound();
            }

            return View(clinic);
        }

        // POST: Clinics/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clinics == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Clinics'  is null.");
            }

            await _httpClient.DeleteAsync("https://localhost:7196/api/ClinicsApi/" + id);
            return RedirectToAction(nameof(Index));
        }

        private bool ClinicExists(int id)
        {
          return (_context.Clinics?.Any(e => e.clinicId == id)).GetValueOrDefault();
        }
    }
}

WebApplication7/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WebApplication7.Data;
using WebApplication7.Models;

namespace WebApplication7.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly HttpClient _httpClient;

        public DoctorsController(ApplicationDbContext context)
        {
            _context = context;
            _httpClient = new HttpClient();
        }

        // GET: Doctors
        public async Task<IActionResult> Index()
        {
            List<Doctor> doktorlar = new List<Doctor>();

            var response = await _httpClient.GetAsync("https://localhost:7196/api/DoctorsApi");
            var jsonResponse = await response.Content.ReadAsStringAsync();
            doktorlar = JsonConvert.DeserializeObject<List<Doctor>>(jsonResponse);
            return View(doktorlar) ;
        }

        // GET: Doctors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            Doctor doctor = new Doctor();

            var response = await _httpClient.GetAsync("https://localhost:7196/api/DoctorsApi/"+ id);
            var jsonResponse = await response.Content.ReadAsStringAsync();
            doctor = JsonConvert.DeserializeObject<Doctor>(jsonResponse);     

            return View(doctor);
        }

        // GET: Doctors/Create
        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            ViewData["clinicId"] = new SelectList(_context.Clinics, "clinicId", "clinicName");
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("doctorId,firstName,lastName,clinicId")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                string data = JsonConvert.SerializeObject(doctor);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage responseMessage = await _httpClient.PostAsync("https://localhost:7196/api/DoctorsApi/", content);

                if (responseMessage.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["clinicId"] = new SelectList(_context.Clinics, "clinicId", "clinicName", doctor.clinicId);
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors.FindAsync(id);
            if (doctor == null)
            {
                return NotFound();
            }
            ViewData["clinicId"] = new SelectList(_context.Clinics, "clinicId", "clinicName", doctor.clinicId);
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("doctorId,firstName,lastName,clinicId")] Doctor doctor)
        {
            if (ModelState.IsValid)
            { 
                 string data = JsonConvert.SerializeObject(doctor);
                 StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                 HttpResponseMessage responseMessage = await _httpClient.PutAsync("https://localhost:7196/api/DoctorsApi/" + id, content);

                if(responseMessage.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            ViewData["clinicId"] = new SelectList(_context.Clinics, "clinicId", "clinicName", doctor.clinicId);
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
                .Include(d => d.clinic)
                .FirstOrDefaultAsync(m => m.doctorId == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Doctors == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Doctors'  is null.");
            }

            await _httpClient.DeleteAsync("https://localhost:7196/api/DoctorsApi/" + id);
            return RedirectToAction(nameof(Index));
        }

        private bool DoctorExists(int id)
        {
          return (_context.Doctors?.Any(e => e.doctorId == id)).GetValueOrDefault();
        }
    }
}

WebApplication7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication7.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                

                @if (User.IsInRole("Admin"))
                {

                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MHRS (Admin)</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="Index">@_localization.Getkey("DoktorDuzenleme").Value</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clinics" asp-action="Index">@_localization.Getkey("KlinikDuzenleme").Value</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">@_localization.Getkey("RandevuDuzenleme").Value</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                        <div class="dropdown">
                            <button type="button"
                                    class="btn btn-primary dropdown-toggle"
                                    data-bs-toggle="dropdown">
                                @_localization.Getkey("DilSecenegi").Value
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a asp-controller="Home"
                                       asp-action="ChangeLanguage"
                                       asp-route-culture="tr-TR"
                                       class="dropdown-item">
                                        <i class="flag-icon flag-icon-gb"></i> Türkçe
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Home"
                                       asp-action="ChangeLanguage"
                                       asp-route-culture="en-US"
                                       class="dropdown-item">
                                        <i class="flag-icon flag-icon-gb"></i> English
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                }
                @if (User.IsInRole("User"))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MHRS</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Reserve">@_localization.Getkey("RandevuAl").Value</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="MyAppointments">@_localization.Getkey("Randevularım").Value</a>
                        </li>
                    </ul>
                        
                    <partial name="_LoginPartial" />
                    
                        <div class="dropdown">
                            <button style="width: 200px" type="button"
                                    class="btn btn-primary dropdown-toggle"
                                    data-bs-toggle="dropdown">
                                @_localization.Getkey("DilSecenegi").Value
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a asp-controller="Home"
                                       asp-action="ChangeLanguage"
                                       asp-route-culture="tr-TR"
                                       class="dropdown-item">
                                        <i class="flag-icon flag-icon-gb"></i> Türkçe
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Home"
                                       asp-action="ChangeLanguage"
                                       asp-route-culture="en-US"
                                       class="dropdown-item">
                                        <i class="flag-icon flag-icon-gb"></i> English
                                    </a>
                                </li>
                            </ul>
                        </div>
            
                </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - MHRS 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>